CREATE TABLE `web-planner`.`events`
( `id` INT NOT NULL AUTO_INCREMENT , `facultyNumber` INT NOT NULL , `name` VARCHAR
(100) NOT NULL , PRIMARY KEY
(`id`)) ENGINE = InnoDB;

ALTER TABLE `events`
ADD FOREIGN KEY
(`id`) REFERENCES `users`
(`id`) ON
DELETE RESTRICT ON
UPDATE RESTRICT;

ALTER TABLE `events`
ADD `start` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `name`,
ADD UNIQUE
(`start`);

ALTER TABLE `events`
ADD `
end` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `start`,
ADD UNIQUE
(`
end`);